config/routes.rb
Singchana::Application.routes.draw do

  get "songs/index"
  get "songs/search"
  get "songs/artist/:id" => "songs#artist"
  get "songs/album/:id" => "songs#album"
  
  get "karaoke/:id" => "karaoke#index", :constraints => {:id => /\d+/}, :as => "karaoke"
  get "karaoke/song_transcript"
  post "karaoke/submit_score"
  match "new" => "admin#new", :as => :new_admin
  match "admin_create" => "admin#admin_create", :as => :admin_create
  match "admin_login" => "admin#admin_login", :as => :login1
  match "login_admin" => "admin#login_admin", :as => :login
  match "/admin/dashboard" => "admin#dashboard"
  match "logout" => "admin#logout", :as => :log_out

  match "dashboard" => "admin#dashboard", :as => :dashboard
  match "create"  => "admin#create",  :as => :create_song

  match "new_album" => "album#new_album", :as => :new_album
  match "create_album" => "album#create_album", :as => :create_album

  match "new_artist" => "artist#new_artist", :as => :new_artist
  match "create_artist" => "artist#create_artist", :as => :create_artist

  match "new_music" => "music#new_music", :as => :new_music
  match "create_music" => "music#create_music", :as => :create_music
  match "admin_logout" => "admin#admin_logout", :as => :admin_logout

  match "add_song" => "admin#add_song",  :as => :add_song

  match "music_list" => "music#music_list", :as => :music_list
  match "album_list" => "album#album_list", :as => :album_list
  match "artist_list" => "artist#artist_list", :as => :artist_list

  match "edit_musics/:id" => "music#edit_musics", :as => :edit_music
  match "destroy_music/:id" => "music#destroy_music",  :as => :destroy_music
  match "/edit/:id" => "music#edit", :as => :edit_music_type

  match "edit_album/:id" => "album#edit_album", :as => :edit_album
  match "destroy_album/:id" => "album#destroy_album",  :as => :destroy_album
  match "/album_edit/:id" => "album#album_edit", :as => :edit_album_type

  match "edit_artist/:id" => "artist#edit_artist", :as => :edit_artist
  match "destroy_artist/:id" => "artist#destroy_artist",  :as => :destroy_artist
  match "/artist_edit/:id" => "artist#artist_edit", :as => :edit_artist_type

  resources "users"
  resources "album"
  resources "artist"
  resources "music"
  resource "user_session", only: %w(new create destroy)
  resource "password_reset", only: %w(new create edit update)

  root :to => 'songs#index'

end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
  belongs_to :user
  belongs_to :badge
  
  validates :user_id, :presence => true
  validates :badge_id, :presence => true
  
  validates_uniqueness_of :badge_id, :scope => :user_id
  
  def self.grant(user_id, badge_id)
    Achievement.create({ user_id: user_id, badge_id: badge_id })
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessible :email, :password_hash, :password_salt, :password, :password_confirmation
  attr_accessor :password
  before_save :encrypt_password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
    end
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :songs
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs
end

app/models/badge.rb
class Badge < ActiveRecord::Base
  validates :name, :presence => true
  validates :category, :presence => true
  validates :description, :presence => true
  validates :required_value, :presence => true, :numericality => true
end

app/models/entertainment.rb
class Entertainment < ActiveRecord::Base
   attr_accessible :music

  has_attached_file :music, 

  :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
               :url => "/system/:attachment/:id/:style/:filename"
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :genre_assignments
  has_many :songs, :through => :genre_assignments
end

app/models/genre_assignment.rb
class GenreAssignment < ActiveRecord::Base
end

app/models/karaoke_session.rb
class KaraokeSession < ActiveRecord::Base
  belongs_to :user
  belongs_to :song
  
  validates :user_id, :presence => true
  validates :song_id, :presence => true
  
  validates_presence_of :score, :if => :ended?
  
  def self.start(user_id, song_id)
    KaraokeSession.create!({ user_id: user_id, song_id: song_id })
  end
  
  def finalize!
    self.ended = true
    begin
      self.save!
    rescue
      self.ended = false
      raise
    end
  end
  
  def ended?
    (self.ended == true) || false
  end
end

app/models/music.rb
class Music < ActiveRecord::Base
   attr_accessible  :name
end

app/models/song.rb
# This class represents a Karaoke Song.
class Song < ActiveRecord::Base
  belongs_to :artist
  belongs_to :album
  has_many :genre_assignments
  has_many :genres, :through => :genre_assignments

  validates :title, :presence => true



  # Given a set of search terms, lookup for any associated song records.
  # Each term will be queried against song's title, artist's name, and album's title.
  # The set of song records associated with each term will be intersected to produce the final result.
  def self.search(terms)

    songs_for_term = [] # Set of songs associated with each term.
    terms.each_index do |index|
      songs_for_term[index] = Song.order("songs.id desc").
          includes(:artist).includes(:album).
          joins("LEFT JOIN artists ON songs.artist_id = artists.id").
          joins("LEFT JOIN albums ON songs.album_id = albums.id").
          where("LOWER(songs.title) LIKE :term OR LOWER(artists.name) LIKE :term OR LOWER(albums.title) LIKE :term", 
              :term => "%#{terms[index].downcase}%")
    end
    
    # Intersect the set of songs against each other.
    songs = songs_for_term[0] || []
    songs_for_term.each_index do |index|
      next if index == 0
      songs = songs & songs_for_term[index] # Intersection.
    end 
    
    return songs
  end
    
  # Return the song's file URL.
  def file_url
    sprintf("%s/%05d.mp3", Singchana::Application.config.song_file_path, self.id)
  end
  
  # Return the song's transcript as a string (XML format).
  def transcript
    file_name = sprintf("%s/%05d.xml", Singchana::Application.config.transcript_file_path, self.id)
    IO.read(file_name) # Return file's content.
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :karaoke_sessions

  # Enable AuthLogic authentication.
  acts_as_authentic do |c|
    # Password reset token will be valid for specified time.
    c.perishable_token_valid_for = 1.hour
    c.crypto_provider = Authlogic::CryptoProviders::Sha512
  end

  attr_accessible :name, :email, :password, :password_confirmation, :terms_and_condition
  
  # These attributes will only be used during user account creation.
  attr_accessor :terms_and_condition
  
  # Validation declaration
  validates :name, :presence => true, :length => { :minimum => 2 }  
  validates :terms_and_condition, :acceptance => true, :on => :create
  
  def sing_count
    self.karaoke_sessions.where(:ended => true).count
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/karaoke_helper.rb
module KaraokeHelper
end

app/helpers/music_helper.rb
module MusicHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_search_panel.html.erb
<script>
  $(function() {
    var searchInput = $('#search_input').livesearch({ url: '/songs/search', minChar: 3 });
    
    // Action to perform on search success
    searchInput.bind('success', function(event, data) {
      $('#search_result').html(data);
    });
    
    searchInput.bind('progress', function(event) {
      $('#search_indicator').addClass('progress');
    });
    
    searchInput.bind('complete', function(event) {
      $('#search_indicator').removeClass('progress');
    });
    
    $('#search_indicator').click(function() { $('#search_result').html(''); });
  });
</script>

<div id="search_panel" class="panel">
  <div class="header">

    <input type="text" id="search_input" placeholder="Find song, artist, album"></input>
    <span id="search_indicator">&nbsp;</span>

    <div class="buttons">
      <button>Song</button>
      <button>Song list</button>
    </div>
    
    <div class="clear"></div>
  </div>
    
  <ul class="content" id="search_result"></ul>
</div>

app/views/admin/add_song.html.erb
<script>
  $(document).ready(function() {
  $("#button").bind("click", function() {
    /* Generating unique id
    */
   var num     = $('.clonedInput').length;
   var newNum  = new Number(num + 1);
    var rand = Math.random().toString().split(".")[1];
    var input = '<input type="file" name="music[]" class="music['+newNum+']" />'

    $(this).before('<br/>' + input );
  });

  /* Pushing the first input to the DOM
  */
  $("#button").trigger("click");

});
</script>


<%= form_for(@song, :as => :song, :url => create_song_path,:html => {:multipart => true}, :method => "post") do |f| %>
<h2>Add Songs.......................</h2>

<div>
  <label>Music Title :</label><br/>
  <%= f.text_field :title %>

</div>

<div>
  <label>Select Artist :</label><br/>
  <%= select(:song, :artist_id, @artist.collect {|p| [p.name,p.id]  }, {:prompt => 'Select Artist'})%>
</div>

<div>
  <label>Select Album :</label><br/>
  <%= select(:song, :album_id, @album.collect {|p| [p.title,p.id]  }, {:prompt => 'Select Album'})%>
</div>

<div>
  <label>Select Music Type :</label><br/>
  <%= select(:song, :music_id, @music.collect {|p| [p.name,p.id]  }, {:prompt => 'Select Music Type'})%>
</div>

   <div class="file">
                               <div class="clonedInput" id="input1">

                            <label>Upload File</label>


                            <div class="clear"></div>
                            <a href="javascript:void(0)" id="button">Add more</a>
                            <div class="clear"></div>
                            <div class="ations">
                             <input type="submit" id="save" class="save" value="Submit"/>
                            </div>
  </div>
   </div>



<% end %>

app/views/admin/admin_login.html.erb
<%= form_for(@login, :as => :login, :url => login_path, :method => "post") do |f| %>
<p>
<%= label_tag :email %><br />
<%= text_field_tag :email, params[:email] %>
</p>
<p>
<%= label_tag :password %><br />
<%= password_field_tag :password %>
</p>
<p class="button"><%= submit_tag %></p>
<% end %>

app/views/admin/dashboard.html.erb
<h2> Welcome Admin</h2>
<script>
  $(function() {
    scroll_pane = $('#popular_songs').jScrollPane({ showArrows: true });
  });
</script>

<%= render :partial => 'search_panel' %>

<div class="panel">
  <div class="header">
    <h2>Popular Songs</h2>
    <div class="buttons">
      <button>Today</button>
      <button>Last week</button>
      <button>This month</button>
      <button>All time</button>
    </div>
    <div class="clear"></div>
  </div>

  <div class="content">

    <ul id="popular_songs">
<audio controls="controls">
  <source src="public/system/musics/1/original/32_EK_TERA_SAATH.mp3" type="audio/ogg" />
  <source src="horse.mp3" type="audio/mp3" />


  <audio_tag("32_EK_TERA_SAATH.mp3", :autoplay => true, :controls => true)  # =>
  <audio autoplay="autoplay" controls="controls" src="public/system/musics/1/original/32_EK_TERA_SAATH.mp3" />
  Your browser does not support the audio element.
</audio>
       <embed height="100" width="100" src="public/system/musics/1/original/32_EK_TERA_SAATH.mp3" />

      <%# @songs.each do |song| %>
        <%#*<li class="song">%>
          <%#= link_to karaoke_path(song.id) do %>
            <%#= image_tag('sample_album_pict.jpg', :alt => song.title) %>
          <%# end %>
          <%#*<p class="song_title"><%= song.title %></p>%>
          <%#*<p class="song_artist">by <%= song.artist.name %></p>%>
        <%#*</li>%>
      <%# end %>
    </ul>
  </div>
</div>

app/views/admin/new.html.erb
<div id="create_account_panel" class="popup_panel">
  <ul class="breadcrumb">
    <li class="current">New account</li>
    <li>Your voice</li>
    <li>Your face</li>
    <li>Let's sing!</li>
  </ul>

<%=  form_for(@admin, :as => :admin, :url => admin_create_path, :method => "post") do |f| %>
  <div class="content">
    <h2>Account Details</h2>

    <div>
      <%= f.label :email %>:<br/>
      <%= f.email_field :email, :placeholder => 'Your e-mail' %>
    </div>
    <div>
      <%= f.label :password %>:<br/>
      <%= f.password_field :password, :placeholder => 'Your password' %>
    </div>

    <div>
      <%= f.label :password_confirmation %>:<br/>
      <%= f.password_field :password_confirmation %>
    </div>
    
    <div>
      <%= f.submit :Login %>
    </div>
  </div>
 <% end %>

</div>

app/views/anonymous/create.html.erb
<!-- Dummy view template for testing anonymous controller in RSpec -->

app/views/anonymous/index.html.erb
<!-- Dummy view template for testing anonymous controller in RSpec -->

app/views/anonymous/new.html.erb
<!-- Dummy view template for testing anonymous controller in RSpec -->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Singchana</title>
  <%= csrf_meta_tags %>

  <%= javascript_include_tag "application" %>

  <%= stylesheet_link_tag "application" %>
  <!--[if IE]> <%= stylesheet_link_tag "application_ie" %> <![endif]-->

  <script>
    $(function() { $('a.popup').colorbox(); });
  </script>
</head>
<body>
  <div id="topbar">
    <div id="logo"><a href="/admin/dashboard"><%= image_tag 'singchana_logo.png', :alt => 'Singchana' %></a></div>

    <ul id="topmenu">

      <li class="menu-division" />

      <%#*<li><a href="#">Music Library</a></li><li class="menu-division" />%>
      <%#*<li><a href="#">Best Users</a></li><li class="menu-division" />%>
      <%#*<li><a href="#">Event</a></li><li class="menu-division" />%>
      <%#*<li><a href="#">Help</a></li><li class="menu-division" />%>




<li> <%= link_to "Add Music",add_song_path %></li>


      <li class="submenu">
        <a href="#">&nbsp;&nbsp; Artist &nbsp;&nbsp;</a>
              <ul>
            <li> <%= link_to "create",new_artist_path %></li>

            <li><%= link_to "Artist list", artist_list_path%></li>
        </ul>
      </li>



        <li class="submenu">
        <a href="#">&nbsp;&nbsp; Album &nbsp;&nbsp;</a>
              <ul>
            <li> <%= link_to "create", new_album_path %></li>

            <li><%= link_to "Album list", album_list_path%></li>
        </ul>
      </li>

      <li class="submenu">
        <a href="#">&nbsp;&nbsp; Music Type &nbsp;&nbsp;</a>
              <ul>
            <li> <%= link_to "create", new_music_path %></li>

            <li><%= link_to "Music list", music_list_path%></li>
        </ul>
      </li>

      <li class="submenu">
        <a href="#">&nbsp; &nbsp; Admin</a>
        <ul>
          <% if current_admin.nil? %>
            <li><%= link_to "Log in", login1_path, :class => 'popup' %></li>
            <li><%= link_to "Sign up", new_admin_path, :class => 'popup' %></li>
          <% elsif %>
            <li><%= link_to "Log out", log_out_path %></li>
          <% end %>
        </ul>
      </li>

    </ul>
  </div>
  <div style="float:none; clear:both;"></div>

  <div id="content">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :class => name %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Singchana</title>
  <%= csrf_meta_tags %>
  
  <%= javascript_include_tag "application" %>
  
  <%= stylesheet_link_tag "application" %>
  <!--[if IE]> <%= stylesheet_link_tag "application_ie" %> <![endif]-->
  
  <script>
    $(function() { $('a.popup').colorbox(); });
  </script>
</head>
<body>
  <div id="topbar">
    <div id="logo"><a href="/"><%= image_tag 'singchana_logo.png', :alt => 'Singchana' %></a></div>
    
    <ul id="topmenu">
          
      <li class="submenu">
        <a href="#">Account</a>
        <ul>
          <% if current_user_session.nil? %>
            <li><%= link_to "Log in", new_user_session_path, :class => 'popup' %></li>
            <li><%= link_to "Sign up", new_user_path, :class => 'popup' %></li>
          <% elsif %>
            <li><%= link_to "Log out",log_out_path %></li>
          <% end %>
        </ul>
      </li>
      <li class="menu-division" />
          
      <li><a href="#">Music Library</a></li><li class="menu-division" />
      <li><a href="#">Best Users</a></li><li class="menu-division" />      
      <li><a href="#">Event</a></li><li class="menu-division" />
      <li><a href="#">Help</a></li><li class="menu-division" />

      <li class="submenu">
        <a href="#">&nbsp; &nbsp; Admin</a>
        <ul>
          <% if current_admin.nil? %>
            <li><%= link_to "Log in", login1_path, :class => 'popup' %></li>
            <li><%= link_to "Sign up", new_admin_path, :class => 'popup' %></li>
          <% elsif %>
            <li><%= link_to "Log out", user_session_path, :method => :delete %></li>
          <% end %>
        </ul>
      </li>

    </ul>
  </div>
  <div style="float:none; clear:both;"></div>
  
  <div id="content">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :class => name %>
    <% end %>
    
    <%= yield %>
  </div>
</body>
</html>

app/views/shared/_error.html.erb
<%= content_tag :div, error, class: 'error' %>

app/views/shared/error.html.erb
<%= render partial: 'shared/error', error: @error %>

app/views/shared/error.js.erb
console.error('<%= @error %>')

app/views/shared/redirection.js.erb
window.location = <%= @redirect_url %>;