config/routes.rb
Singchana::Application.routes.draw do

  get "songs/index"
  get "songs/search"
  get "songs/artist/:id" => "songs#artist"
  get "songs/album/:id" => "songs#album"
  
  get "karaoke/:id" => "karaoke#index", :constraints => {:id => /\d+/}, :as => "karaoke"
  get "karaoke/song_transcript"
  post "karaoke/submit_score"
  match "new" => "admin#new", :as => :new_admin
  match "admin_create" => "admin#admin_create", :as => :admin_create
  match "admin_login" => "admin#admin_login", :as => :login1
  match "login_admin" => "admin#login_admin", :as => :login
  match "/admin/dashboard" => "admin#dashboard"
  match "logout" => "admin#logout", :as => :log_out

  match "dashboard" => "admin#dashboard", :as => :dashboard
  match "create"  => "admin#create",  :as => :create_song

  match "new_album" => "album#new_album", :as => :new_album
  match "create_album" => "album#create_album", :as => :create_album

  match "new_artist" => "artist#new_artist", :as => :new_artist
  match "create_artist" => "artist#create_artist", :as => :create_artist

  match "new_music" => "music#new_music", :as => :new_music
  match "create_music" => "music#create_music", :as => :create_music
  match "admin_logout" => "admin#admin_logout", :as => :admin_logout

  match "add_song" => "admin#add_song",  :as => :add_song

  match "music_list" => "music#music_list", :as => :music_list
  match "album_list" => "album#album_list", :as => :album_list
  match "artist_list" => "artist#artist_list", :as => :artist_list

  match "edit_musics/:id" => "music#edit_musics", :as => :edit_music
  match "destroy_music/:id" => "music#destroy_music",  :as => :destroy_music
  match "/edit/:id" => "music#edit", :as => :edit_music_type

  match "edit_album/:id" => "album#edit_album", :as => :edit_album
  match "destroy_album/:id" => "album#destroy_album",  :as => :destroy_album
  match "/album_edit/:id" => "album#album_edit", :as => :edit_album_type

  match "edit_artist/:id" => "artist#edit_artist", :as => :edit_artist
  match "destroy_artist/:id" => "artist#destroy_artist",  :as => :destroy_artist
  match "/artist_edit/:id" => "artist#artist_edit", :as => :edit_artist_type

  resources "users"
  resources "album"
  resources "artist"
  resources "music"
  resource "user_session", only: %w(new create destroy)
  resource "password_reset", only: %w(new create edit update)

  root :to => 'songs#index'

end

app/models/music.rb
class Music < ActiveRecord::Base
   attr_accessible  :name
end

app/controllers/music_controller.rb
class MusicController < ApplicationController
  def new_music
    @music = Music.new
    render :layout => "admin"
  end

  def create_music
   params[:music].each do |mu|
    @music = Music.create(:name => mu)
    @music.save
   end
    redirect_to (new_music_path)
  end

  def music_list
    @music_list = Music.all
    render :layout => "admin"
  end

  def edit_musics
    @edit_music = Music.find_by_id(params[:id])
    render :layout => "admin"
  end

  def edit
    @edit_music = Music.find_by_id(params[:id])
    @edit_music.update_attributes(params[:music])
    redirect_to (music_list_path)
  end

  def destroy_music
    @delete_music = Music.find_by_id(params[:id])
    @delete_music.destroy
    redirect_to (music_list_path)
  end
end

app/helpers/music_helper.rb
module MusicHelper
end

app/views/music/edit_musics.html.erb
<h2>Edit Music...............................!</h2>

<%= form_for(@edit_music, :as=> :music, :url => {:controller => "music", :action => "edit"}, :method => "post", :id => @edit_music.id ) do |f| %>
<label>Music Type</label>
  <%= f.text_field :name  %><br/>
<%= f.submit :Update %>
<%end%>

app/views/music/music_list.html.erb
<h2>Music List................................!</h2>
<div id="restaurant-1">
                       <table class="tabledes lft_aln">

                        <thead>
                          <tr>
                                <th>S#</th>
                                <th>Music Type</th>
                                <th>Actions</th>
                            </tr>
                        </thead>

                        <tbody>
                           <%if @music_list.nil?%>
                          <h4>There are no Music Type to show under this Music List.</h4>
                            <%end%>

                          <%@count=0%>
                           <% @music_list.each do |mu| %>
                            <tr class="alt">
                                <td><%=@count+= 1  %></td>
                                <td><%= mu .name%></td>
                                <td>

                                <div class="action group rest-list-act">
                                      <%= link_to 'Edit', :controller => "music", :action => "edit_musics", :class => "popup" , :id => mu.id%>
                                            <span>/</span>
                                            <%= link_to 'Delete',:controller => "music", :action => "destroy_music", :id =>mu.id %>
                                            
                                </div></td>
                            </tr>
                            <%end%>

                               </tbody>

                    </table>
                     </div>

app/views/music/new_music.html.erb
<h2>Music..............................!</h2>

<script>
  $(document).ready(function() {
  $("#button").bind("click", function() {
    /* Generating unique id
    */
   var num     = $('.clonedInput').length;
   var newNum  = new Number(num + 1);
    var rand = Math.random().toString().split(".")[1];
    var input = '<input type="text" name="music[]" class="music['+newNum+']" />'

    $(this).before('<br/>' + input );
  });

  /* Pushing the first input to the DOM
  */
  $("#button").trigger("click");

});
</script>

<%= form_for(@music, :as =>:music, :url => create_music_path, :method => "post") do |f| %>
<div class="field">
                               <div class="clonedInput" id="input1">

                            <label>Music Type</label>
                            <div class="clear"></div>
                            <a href="javascript:void(0)" id="button">Add more</a>
                            <div class="clear"></div>
                            <div class="ations">
                             <input type="submit" id="save" class="save" value="Submit"/>
                            </div>
  </div>
  </div>
<% end %>