config/routes.rb
Singchana::Application.routes.draw do

  get "songs/index"
  get "songs/search"
  get "songs/artist/:id" => "songs#artist"
  get "songs/album/:id" => "songs#album"
  
  get "karaoke/:id" => "karaoke#index", :constraints => {:id => /\d+/}, :as => "karaoke"
  get "karaoke/song_transcript"
  post "karaoke/submit_score"
  match "new" => "admin#new", :as => :new_admin
  match "admin_create" => "admin#admin_create", :as => :admin_create
  match "admin_login" => "admin#admin_login", :as => :login1
  match "login_admin" => "admin#login_admin", :as => :login
  match "/admin/dashboard" => "admin#dashboard"
  match "logout" => "admin#logout", :as => :log_out

  match "dashboard" => "admin#dashboard", :as => :dashboard
  match "create"  => "admin#create",  :as => :create_song

  match "new_album" => "album#new_album", :as => :new_album
  match "create_album" => "album#create_album", :as => :create_album

  match "new_artist" => "artist#new_artist", :as => :new_artist
  match "create_artist" => "artist#create_artist", :as => :create_artist

  match "new_music" => "music#new_music", :as => :new_music
  match "create_music" => "music#create_music", :as => :create_music
  match "admin_logout" => "admin#admin_logout", :as => :admin_logout

  match "add_song" => "admin#add_song",  :as => :add_song

  match "music_list" => "music#music_list", :as => :music_list
  match "album_list" => "album#album_list", :as => :album_list
  match "artist_list" => "artist#artist_list", :as => :artist_list

  match "edit_musics/:id" => "music#edit_musics", :as => :edit_music
  match "destroy_music/:id" => "music#destroy_music",  :as => :destroy_music
  match "/edit/:id" => "music#edit", :as => :edit_music_type

  match "edit_album/:id" => "album#edit_album", :as => :edit_album
  match "destroy_album/:id" => "album#destroy_album",  :as => :destroy_album
  match "/album_edit/:id" => "album#album_edit", :as => :edit_album_type

  match "edit_artist/:id" => "artist#edit_artist", :as => :edit_artist
  match "destroy_artist/:id" => "artist#destroy_artist",  :as => :destroy_artist
  match "/artist_edit/:id" => "artist#artist_edit", :as => :edit_artist_type

  resources "users"
  resources "album"
  resources "artist"
  resources "music"
  resource "user_session", only: %w(new create destroy)
  resource "password_reset", only: %w(new create edit update)

  root :to => 'songs#index'

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  respond_to :js, :only => [:create]

  def new
    session[:form_referrer] = request.referrer
    @user_session = UserSession.new
  end
  
  def create
    @user_session = UserSession.new(params[:user_session])
    
    if @user_session.save
      flash[:notice] = "User logged in (#{current_user.email})" 
      @redirect_url = session[:form_referrer] || root_url
    end
      
    respond_with @user_session
  end
  
  def destroy
    current_user_session.destroy if current_user_session
    redirect_to root_url, :notice => "Successfully logged out!"
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/create.js.erb
<% if @redirect_url.present? %>
  window.location = '<%= @redirect_url %>'
<% end %>

<% if @user_session.errors.any? %>
  // Display error message.
  $('#login_message').removeClass('hidden').addClass('error');
  $('#login_message').html('Invalid e-mail or password');
  
  // Resize colorbox popup
  $.colorbox.resize();
<% end %>

app/views/user_sessions/new.html.erb
<script>
  $(function() { $('a.popup').colorbox(); });
</script>

<div id="login_panel" class="popup_panel">
  <h2>Log in <span>(or create <%= link_to "new account", new_user_path, :class => 'popup' %>)</span></h2>

  <%= form_for @user_session, :id => 'login_form', :url => user_session_path, :remote => true do |f| %>
  
    <div class="content">
      <%= content_tag :div, nil, :id => 'login_message', :class => 'hidden' %>

      <div>
        <%= f.label :email %>
        <%= f.text_field :email, :placeholder => 'Your e-mail' %>
      </div><div>
        <%= f.label :password %>
        <%= f.password_field :password, :placeholder => 'Your password' %>
      </div><div>
        <%= link_to "Forgot your password?", new_password_reset_path, class: 'popup' %>
      </div>
    </div>
  
    <div class="footer">
      <p>
        <%= f.check_box :remember_me %> 
        <span>Please keep me logged in</span>
      </p>
      <div><%= f.submit 'Log in', disable_with: 'Logging in...', class: 'ok' %></div>
    </div>
  
  <% end %>
</div>